#!/bin/bash
# Manage scheduled backups by generating a cron.d file from a
# schedules config (domain, driver, cron expression per line).
#
# Usage:
#   scheduler.sh install [--schedules FILE] [--config FILE] [--cron-file FILE]
#   scheduler.sh list [--schedules FILE]
set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/lib/common.sh"

SCHEDULES="/etc/borgbackup/schedules.conf"
CONFIG="/etc/borgbackup/borgbackup.conf"
CRON_FILE="/etc/cron.d/borgbackup"
CMD="${1:-}"
shift || true

while [ $# -gt 0 ]; do
    case "$1" in
        --schedules) SCHEDULES="$2"; shift 2 ;;
        --config) CONFIG="$2"; shift 2 ;;
        --cron-file) CRON_FILE="$2"; shift 2 ;;
        *) die "unknown argument: $1" ;;
    esac
done

[ -f "$SCHEDULES" ] || die "schedules file not found: $SCHEDULES"

read_schedules() {
    grep -Ev '^\s*(#|$)' "$SCHEDULES"
}

case "$CMD" in
    list)
        printf "%-24s %-6s %s\n" "DOMAIN" "DRIVER" "SCHEDULE"
        while read -r domain driver cron_expr; do
            printf "%-24s %-6s %s\n" "$domain" "$driver" "$cron_expr"
        done < <(read_schedules)
        ;;
    install)
        log "Writing cron jobs to ${CRON_FILE}"
        {
            echo "# Generated by scheduler.sh from ${SCHEDULES} - do not edit by hand"
            while read -r domain driver cron_expr; do
                echo "${cron_expr} root ${SCRIPT_DIR}/backup.sh --domain ${domain} --driver ${driver} --config ${CONFIG} >> /var/log/borgbackup/${domain}.log 2>&1"
            done < <(read_schedules)
        } | sudo tee "$CRON_FILE" >/dev/null
        sudo mkdir -p /var/log/borgbackup
        log "Installed $(read_schedules | wc -l) scheduled job(s)"
        ;;
    *)
        die "usage: scheduler.sh install|list [--schedules FILE] [--config FILE] [--cron-file FILE]"
        ;;
esac
