<?php
declare(strict_types=1);

// Regenerates the cron.d file from the schedules table. Each enabled
// schedule gets its own persistent per-domain config + passphrase file
// under domains_conf_dir (0600, root-readable only), since scheduled runs
// happen outside any PHP request and can't get a passphrase decrypted
// on the fly the way manual triggers do.
function regenerate_cron(): void
{
    $cfg = $GLOBALS['config'];
    $confDir = rtrim($cfg['domains_conf_dir'], '/');
    if (!is_dir($confDir)) {
        mkdir($confDir, 0700, true);
    }

    $stmt = db()->query(
        'SELECT s.cron_expr, d.name, d.driver, r.repo_path, r.keep_within, c.encrypted_passphrase
         FROM schedules s
         JOIN domains d ON d.id = s.domain_id
         JOIN repos r ON r.id = d.repo_id
         JOIN credentials c ON c.id = r.credential_id
         WHERE s.enabled = TRUE
         ORDER BY d.name'
    );

    $lines = ['# Generated by the BorgBackup GUI - do not edit by hand'];
    foreach ($stmt as $row) {
        $passFile = "{$confDir}/{$row['name']}.pass";
        $confFile = "{$confDir}/{$row['name']}.conf";

        file_put_contents($passFile, decrypt_secret($row['encrypted_passphrase']));
        chmod($passFile, 0600);

        $conf = "BORG_REPO=" . escapeshellarg($row['repo_path']) . "\n"
              . "BORG_PASSPHRASE_FILE=" . escapeshellarg($passFile) . "\n"
              . "KEEP_WITHIN=" . escapeshellarg($row['keep_within']) . "\n";
        file_put_contents($confFile, $conf);
        chmod($confFile, 0600);

        $lines[] = sprintf(
            '%s root %s/backup.sh --domain %s --driver %s --config %s >> /var/log/borgbackup/%s.log 2>&1',
            $row['cron_expr'],
            $cfg['scripts_dir'],
            escapeshellarg($row['name']),
            escapeshellarg($row['driver']),
            escapeshellarg($confFile),
            $row['name']
        );
    }

    file_put_contents($cfg['cron_file'], implode("\n", $lines) . "\n");
    chmod($cfg['cron_file'], 0644);
}
